apiVersion: apps/v1
kind: Deployment
metadata:
  name: jvm-deployment
spec:
  selector:
    matchLabels:
      app: jvm
  replicas: 2
  template:
    metadata:
      labels:
        app: jvm
    spec:
      containers:
      - name: jvm-cn
        image: pranay18cr/jvm-image:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080



---
apiVersion: v1
kind: Service
metadata:
  name: jvm-svc
spec:
  selector:
    app: jvm
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer
